[features]
seeds = false
[programs.localnet]
neon_todo = "BsZzhuvDyCeJRcLGUUo1Sjh6QCb7vRLjE9KMpXta7UyH"

[programs.devnet]
neon_todo = "BsZzhuvDyCeJRcLGUUo1Sjh6QCb7vRLjE9KMpXta7UyH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"